[project]
name = "trellis2"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "o-voxel"
]

[tool.uv.workspace]
members = ["o-voxel"]

[tool.uv.sources]
o-voxel = { workspace = true }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["trellis2", "trellis2.*"]
